version: '2'
services:
  app:
    build: .
    image: test/sample-alpine-rails
    volumes:
      - .:/var/app
    links:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
